### ISSUE TITLE
Expand Security section

### ISSUE THREAD

**Issue by mwullink** [SIDN/ietf-epp-restful-transport#12]
include
- api keys
- header checking
- rate limiting
- ..

see:
 https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html
https://restfulapi.net/security-essentials/
https://infosec.mozilla.org/guidelines/web_security
https://httpwg.org/specs/rfc9110.html#security.considerations

**Comment by mdavids** [comment]
I believe we have a good start now. Closing issue.
